config/routes.rb
Rails.application.routes.draw do

  # Session Routes
  root 'sessions#new'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'

  # Playlist Routes
  resources :playlists
  resources :playlist_movies, only: [:create]

  # Actor Routes
  resources :actors, only: [:show] do
    get 'search', on: :collection
  end 
  
  # Movie Routes
  get '/homepage', to: 'movies#homepage'
  resources :movies, only: [:show] do 
    get 'search', on: :collection
  end 

  # AI Routes
  resources :ai_movie_routes, only: [:new] do 
    get 'generate', on: :collection
  end 

  # Review Routes
  resources :reviews, only: [:create, :destroy]
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  # GET /homepage
  def homepage
    @popular_movies = Movie.fetch_popular_movies
  end 

  # GET /movies/search
  def search
      @movies = Movie.search_by_title(params[:query])
  end

  # GET /movies/:id (tmdb id)
  def show
    @movie = Movie.find(params[:id])
    @movie.fetch_tmdb_data
    @movie.fetch_actors
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
    def format_currency(currency)
        if currency != "0"
            number_to_currency(currency)
        else
            "N/A"
        end 
    end

    def display_movies_search_results(results)
        if results && !results.empty?
            movies = results.map do |m|
                link_to(m.title, movie_path(m), class: "grey-link")
            end
            raw(movies.join)
        elsif results && results.empty?
            raw("<h1 class='red-heading'>No Movies Found</h1>")
        end
    end 

    def display_movie_reviews(reviews)
        if !reviews.empty?
            reviews = reviews.map do |r|
                review = "<blockquote class='block-quote'>#{r.user.username} Says: #{r.user_review}</blockquote>"
                if r.user_id == current_user.id
                    button = button_to("Remove Review", review_path(r), method: :delete, class: "small-submit-button w-button")
                    review + button
                else 
                    review
                end 
            end
            raw(reviews.join) 
        end 
    end 

    def display_most_popular(movie)
        top_movie_stats =
            """
            <h2 class='movie-title'>#{movie.title}</h2>
            #{"<h3 class='tagline'>#{movie.tagline}</h3>" if movie.tagline != ""}
            <p>Popularity Score<br>#{movie.popularity}</p>
            #{"<p>Budget<br>#{format_currency(movie.budget)}</p>" if movie.budget != "0"}
            #{"<p>Revenue<br>#{format_currency(movie.revenue)}</p>" if movie.budget != "0"}
            #{link_to("Learn More", movie_path(movie), class: "link")}
            """
        raw(top_movie_stats)
    end
    
    def display_movies(movies)
        movies = movies[1...-1].map do |m|
            """
            <div class='movie-card'>
                #{link_to(image_tag("https://image.tmdb.org/t/p/original#{m.poster_path}", 
                sizes: "100vw", loading: "lazy", class: "small-movie-image"), movie_path(m))}
              
                <div class='small-movie-text'>Popularity Score <br> #{m.popularity}</div>
            </div>
            """
        end
        raw(movies.join)
    end

    def display_movie_actor_list(actors)
        actor_count = actors.length

        if actor_count > 0
            first_column = actors[0..(actor_count/2)-1].map do |a|
                link_to(a.name, actor_path(a), class: "grey-link centered")
            end
            
            second_column = actors[(actor_count/2)+1..actor_count].map do |a|
                link_to(a.name, actor_path(a), class: "grey-link centered")
            end
    
            actor_list =  
            """
            <div class='w-col w-col-6'>
                #{first_column.join}
            </div>
            <div class='w-col w-col-6'>
                #{second_column.join}
            </div>
            """
    
            raw(actor_list)
        end 
    end  
end

app/views/movies/homepage.html.erb
<div class="section">
  <div class="container w-container">
    
    <%# Change this class name %>
    <div class="div">
      <%= image_tag("https://image.tmdb.org/t/p/original#{@popular_movies.first.backdrop_path}", 
            sizes: "100vw", loading: "lazy", class: "large-movie-image") %>
            
      <div class="movie-info">
        <%= display_most_popular(@popular_movies.first) %>
      </div>
    </div>
  </div>
</div>

<div class="w-layout-grid bottom-grid">
  <%= display_movies(@popular_movies) %>

  <div id="w-node-f0f549d3-5bc0-daf6-0fa9-6ddc643b6668-6216a644" class="div-block">
    <p class="tmdb-text">Data Brought To You By</p>
    <%= link_to(image_tag("tmdb.svg", width: "356", class: "tmdb-logo"), "https://www.themoviedb.org/", target: :blank) %>
  </div>
</div>

app/views/movies/index.html.erb
<div class="center">
  <h3>AI-Flix contains 344,276 Movies</h3>
  <h3>Search Movie by Name or by Year Released</h3>

  <%= form_tag movies_path, :method => "GET" do %>

    <p><%= label_tag :search, "Movie Begins With" %><br>
    <%= text_field_tag :search, params[:search] %></p>

    <p><%= label_tag :year, "Year Released" %><br>
    <%= select_year 0, start_year: 1970, end_year: 2115, prompt: "Select Year" %></p>

    <p><%= submit_tag "Search" %></p>
  <% end %>
</div>

<div class="list">
  <% if @movies %>
    <h3 class="list-title">We found <%= @movies.count %> Movies</h3>
    
    <% @movies.each do |m| %>
      <p><%= link_to "#{m.title} - #{m.year}", movie_path(m) %></p>
    <% end %>

    <%= will_paginate @movies %>
  <% end %>
</div>

app/views/movies/search.html.erb
<div class="container w-container">
  <div class="small-form">
    <h1 class="white-heading">Search Our Movies</h1>
    <div class="form w-form">
      <%= form_with url: '/movies/search', method: :get, class: 'form' do |f| %>
        <%= f.text_field :query, class: "curved-text-field w-input", required: true %>
        <%= f.submit "Search", class: "small-submit-button w-button" %>
      <% end %>
    </div>

    <div class="search-results">
        <%= display_movies_search_results(@movies) %>
    </div>
    
  </div>
</div>

app/views/movies/show.html.erb
<div class="section">
  <div class="container-columns w-container">
    <div class="div-block">

      <h3 class="title-heading"><%= @movie.title %></h3>
      <%= image_tag("https://image.tmdb.org/t/p/original#{@movie.poster_path}", 
      class: "show-image", loading: "lazy", sizes: "300px") %>

      <p class="tagline-large"><%= %Q{"#{@movie.tagline}"} if !@movie.tagline.blank? %></p>
      <%= link_to("IMDb Profile", "https://imdb.com/title/#{@movie.imdb_id}", class: "yellow-link", target: :blank) %>
    </div>

    <div class="data">
      <h2 class="red-heading small">Budget</h2>
      <p class="data-info-large"><%= format_currency(@movie.budget) %></p>
      <h2 class="red-heading small">Revenue</h2>
      <p class="data-info-large"><%= format_currency(@movie.revenue) %></p>
      <h2 class="red-heading small">Release Date</h2>
      <p class="data-info-large"><%= format_date(@movie.release_date) %></p>
      <h2 class="red-heading small">Overview</h2>
      <p class="data-info-large"><%= @movie.overview %></p>
    </div>
  </div>
</div>

<div class="section">
  <div class="playlist-dropdown w-container">
    <h1 class="red-heading">Add to Playlist</h1>
      <% if current_user.playlists.empty? %>
        <h1 class="white-heading smaller">You have no Playlists</h1>
        <%= link_to("Add a Playlist", new_playlist_path, class: "red-link") %>
      <% else %>
        <div class="w-form">
          <%= form_with scope: 'playlist_movie', url: playlist_movies_path, class: "dropdown-form" do |f| %>
            <%= f.hidden_field :movie_id, value: @movie.id %>
            <%= f.collection_select :playlist_id, current_user.playlists, :id, :name, {}, {class: "select-field w-select"} %>
            <%= f.submit "Add to playlist", class: "small-submit-button w-button" %>
          <% end %>
        </div>
      <% end %>
  </div>
</div>

<div class="section">
  <div class="columns w-row">
    <div class="column-1 w-col w-col-6">
      <h1 class="red-heading">Cast</h1>
      <div class="w-row">
        <%= display_movie_actor_list(@movie.actors) %>
      </div>
    </div>
    <div class="column-2 w-col w-col-6">
      <h1 class="red-heading">Reviews</h1>
        <%= display_movie_reviews(@movie.reviews) %>
      
      <div class="review-form w-form">
        <%= form_with scope: 'review', url: reviews_path, class: "small-form" do |f| %>
          <%= f.text_area :user_review, maxlength: "5000", class: "textarea w-input", placeholder: "Leave a Review" %></p>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.hidden_field :movie_id, value: @movie.id %>
          <%= f.submit "Submit", class: "small-submit-button w-button" %>
        <% end %> 
      </div>
    </div>
  </div>
</div>

<div class="tmdb-section">
  <p class="tmdb-text">Data Brought To You By</p>
  <%= link_to(image_tag("tmdb.svg", width: "356", class: "tmdb-logo"), "https://www.themoviedb.org/", target: :blank)%>
</div>