config/routes.rb
Rails.application.routes.draw do

  # Session Routes
  root 'sessions#new'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'

  # Playlist Routes
  resources :playlists
  resources :playlist_movies, only: [:create]

  # Actor Routes
  resources :actors, only: [:show] do
    get 'search', on: :collection
  end 
  
  # Movie Routes
  get '/homepage', to: 'movies#homepage'
  resources :movies, only: [:show] do 
    get 'search', on: :collection
  end 

  # AI Routes
  resources :ai_movie_routes, only: [:new] do 
    get 'generate', on: :collection
  end 

  # Review Routes
  resources :reviews, only: [:create, :destroy]
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user

  has_many :playlist_movies
  has_many :movies, through: :playlist_movies
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]
  before_action :check_playlist_ownership, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  def index
    @playlists = current_user.playlists
  end

  # GET /playlists/:id
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # POST /playlists
  def create
    @playlist = Playlist.create(playlist_params)
    redirect_to playlist_path(@playlist)
  end

  # GET /playlists/:id/edit
  def edit
  end 

  # PATCH/PUT /playlists/:id
  def update
    @playlist.update(playlist_params)
    redirect_to playlist_path(@playlist)
  end 

  # DELETE /playlists/:id
  def destroy
    @playlist.destroy
    redirect_to playlists_path(@playlist)
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name, :user_id, movie_ids: [])
  end

  def set_playlist
    @playlist = Playlist.find(params[:id])
  end
  
  def check_playlist_ownership
    if !current_user.playlists.include?(@playlist)
        redirect_to playlists_path
    end 
  end 
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
    def display_movies_in_playlist(playlist)
        if playlist.movies.empty?
            raw("<h2 class='white-heading'>No Movies Added</h2>")
        else
            movies = playlist.movies.map do |m|
                "#{link_to(m.title, movie_path(m), target: :_blank, class: "grey-link")}"
            end
            raw(movies.join)  
        end
    end 
end

app/views/playlists/edit.html.erb
<div class="small-form checkboxes">
    <h1 class="white-heading">Edit Playlist</h1>
    <div class="form w-form">

        <%= form_with model: @playlist, class: "form" do |f| %>
            <%= f.text_field :name, class: "curved-text-field w-input" %>
            <%= f.hidden_field :user_id, value: current_user.id %>
        
            <%= f.collection_check_boxes(:movie_ids, @playlist.movies, :id, :title, class: "w-checkbox checkbox-field") do |b| %>
                <label class="w-checkbox checkbox-field">
                    <%= b.check_box(class: "w-checkbox-input checkbox") %>
                    <span class="checkbox-label w-form-label">
                        <%= b.label(class: "checkbox-label w-form-label") %>
                    </span>
                </label>
            <% end %>

            <%= f.submit "Edit Playlist", class: "small-submit-button w-button" %>
        <% end %>

    </div>
</div>

app/views/playlists/index.html.erb
<div class="section">
  <div class="vertically-centered w-container">
    <h1 class="white-heading">User Playlists</h1>

    <% if !@playlists.empty? %>
      <% @playlists.each do |p| %>
        <%= link_to(p.name, playlist_path(p), class: "grey-link") %>
      <% end %>
    <% end %>
    
    <%= link_to("Create Playlist", new_playlist_path, class: "red-link") %>
  </div>
</div>

app/views/playlists/new.html.erb
<div class="small-form">
    <h1 class="white-heading">Create A Playlist</h1>
    <div class="form w-form">
        <%= form_with model: @playlist, class: "form" do |f| %>
            <%= f.text_field :name, class: "curved-text-field w-input" %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.submit "Create", class: "small-submit-button w-button" %>
        <% end %>
    </div>
</div>

app/views/playlists/select._movie.html.erb
<div class="list">
  <p>Select a Playlist to Add Movie</p>

  <% @playlists.each do |p| %>
    <p><%= link_to p.name, add_movie_path(p.id, @movie) %></p>
  <% end %>
</div>

app/views/playlists/select.html.erb
<div class="list">
  <p>Select a Playlist to Add Movie</p>

  <% @playlists.each do |p| %>
    <p><%= link_to p.name, add_movie_path(p.id, @movie) %></p>
  <% end %>
</div>

app/views/playlists/show.html.erb
<div class="section">
  <div class="vertically-centered w-container">
    <h1 class="white-heading"><%= @playlist.name %></h1>
      <%= display_movies_in_playlist(@playlist) %>
      <%= link_to("Search Movies", search_movies_path, class: "red-link") %>
      <%= link_to("Edit Playlist", edit_playlist_path(@playlist), class: "red-link top-margin") %>
      <%= button_to("Delete Playlist", playlist_path(@playlist), method: :delete, class: "delete-button w-button") %>
  </div>
</div>