config/routes.rb
Rails.application.routes.draw do

  # Session Routes
  root 'sessions#new'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create'

  # Playlist Routes
  resources :playlists
  resources :playlist_movies, only: [:create]

  # Actor Routes
  resources :actors, only: [:show] do
    get 'search', on: :collection
  end 
  
  # Movie Routes
  get '/homepage', to: 'movies#homepage'
  resources :movies, only: [:show] do 
    get 'search', on: :collection
  end 

  # AI Routes
  resources :ai_movie_routes, only: [:new] do 
    get 'generate', on: :collection
  end 

  # Review Routes
  resources :reviews, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-wf-page="6095fd62b5d42ef7ea52f8e2" data-wf-site="6095f9bb988701248cc2e7ac">
  <head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">

    <!-- [if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif] -->
    <script type="text/javascript">!function(o,c){var n=c.documentElement,t=" w-mod-";n.className+=t+"js",("ontouchstart"in o||o.DocumentTouch&&c instanceof DocumentTouch)&&(n.className+=t+"touch")}(window,document);</script>

    <title>AI-Flix</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'normalize', media: 'all' %>
    <%= stylesheet_link_tag 'webflow', media: 'all' %>
    <%= stylesheet_link_tag 'ai-flix.webflow', media: 'all' %>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎬</text></svg>">
  </head>

  <body>

    <%# display navbar if logged in %>
    <% if logged_in? %>
      <div data-collapse="medium" data-animation="default" data-duration="400" role="banner" class="navbar w-nav">
        <div class="navbar-container w-container">
          <%= link_to(raw('<h1 class="logo">AI-FLIX</h1>'), homepage_path, class: 'brand w-nav-brand') %>
          <nav role="navigation" class="navmenu w-nav-menu">
            <%= link_to('Home', homepage_path, class: 'nav-link w-nav-link') %>
            <%= link_to('Movies', search_movies_path, class: 'nav-link w-nav-link') %>
            <%= link_to('Actors', search_actors_path, class: 'nav-link w-nav-link') %>
            <%= link_to('Playlists', playlists_path, class: 'nav-link w-nav-link') %>
            <%= link_to('AI-Search', new_ai_movie_route_path, class: 'nav-link w-nav-link') %>
            <%= link_to('Logout', logout_path, class: 'nav-link red w-nav-link') %>
          </nav>
          <div class="menu-button w-nav-button">
            <div class="icon w-icon-nav-menu"></div>
          </div>
        </div>
      </div>
    <% end %>

    <%= yield %>
    
    <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=6095f9bb988701248cc2e7ac" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'webflow' %>
    <!-- [if lte IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif] -->
  </body>
</html>